export const mutations = `#graphql

rewriteTweetWithAi(payload:rewriteTweetWithAiPayload):rewriteTweetWithAiResponse
generateAutomatedReplies(payload:generateAutomatedRepliesPayload):generateAutomatedRepliesResponse
`;
